### PR TITLE
Fix compose view detach

### LINKED ISSUE #289: Compose views + back stack don't work together as expected
Hello there! 👋 

I'm trying to use jetpack compose with `ComposeRibView` like this 

````
class HomeViewImpl private constructor(context: Context) : ComposeRibView(context), HomeView {

  private var bottomBar = mutableStateOf<ComposeView?>(null)
  private var content = mutableStateOf<ComposeView?>(null)

  override val composable: @Composable () -> Unit = {
          Column(
              modifier =
                  Modifier.fillMaxSize().background(MaterialTheme.colors.surface)
          ) {
            Box(modifier = Modifier.fillMaxWidth().weight(1f)) {
              content.value?.invoke()
            }
            bottomBar.value?.invoke()
          }
      }

  override fun getParentViewForSubtree(subtreeOf: Node<*>): MutableState<ComposeView?> {
    return when (subtreeOf) {
      is BottomBar -> bottomBar
      else -> content
    }
  }

  class Factory : HomeView.Factory {
    override fun invoke(p1: Nothing?): (RibView) -> HomeView = { HomeViewImpl(it.context) }
  }
}
````
Backstack uses `content` to show backstack content.
The problem is that when I'm pushing something in the backstack `attachChild` is called before `detachChild`, so my `content` value becomes `null` after attaching the child. Are there any other ways to use compose with backstack ?

### PR DESCRIPTION
**Pull request by zsoltk**
Fixes #289

### CODE REVIEW

File: libraries/rib-compose/src/main/java/com/badoo/ribs/compose/ComposeRibView.kt [hunk 1]
```diff
@@ -50,6 +53,14 @@ abstract class ComposeRibView(
 
     override fun detachChild(child: Node<*>, subtreeOf: Node<*>) {
         child.onDetachFromView()
-        getParentViewForSubtree(subtreeOf).value = null
+
+        // Only detach the same child, or we would remove something unintended.
+        // If there was already another child attached, then this one in
+        // MutableState was overwritten, and already removed from the composition as a result,
+        // so no further action is needed.
+        if (child == lastChildAttached) {
```
Comment (antonshilov) [inline libraries/rib-compose/src/main/java/com/badoo/ribs/compose/ComposeRibView.kt:61]: With the current implementation we have an important difference between `AndroidView` and `ComposeView` attach logic.
For `AndroidView` we **add** the child to the view group. So other children are still there when new one is attached.
But for `ComposeView` we are **replacing**  the previous child in `target:mutableState`. So the default configuration essentially support only one child to be shown. Which is actually the reason of the bug we're fixing in this PR.

Is this difference in attach behavior intended? Users may expect `ComposeView` to behave like `AndroidView`, maybe we should make them the same, or document the differences.
