### PR TITLE
Do not throw exception if we don't have listeners for request code (fixes #37)

### LINKED ISSUE #37: Remove exception from RequestCodeBasedEventStreamImpl
We cannot make sure that it's indeed wrong to receive e.g. activity result with request code that no RIB is listening for.

**Case 1: framework error**
Id was not restored correctly, RIB is listening with new id, result is delivered for old id) - this should be backed up and proven with tests, rather than throwing an exception runtime.

**Case 2: client code error**
Activity start / permission request was launched without subscribing to results - this should be raised via warning.

**Case 3: no error**
External activity was launched with request code not generated by us, we should not care about these

### PR DESCRIPTION
**Pull request by lukaville**
See #37

### CODE REVIEW

File: android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+import com.nhaarman.mockitokotlin2.eq
+import com.nhaarman.mockitokotlin2.mock
+import com.nhaarman.mockitokotlin2.never
+import com.nhaarman.mockitokotlin2.verify
+import io.reactivex.disposables.CompositeDisposable
+import org.junit.After
+import org.junit.Before
+import org.junit.Test
+
+class RequestCodeBasedEventStreamImplTest {
```
Comment (zsoltk) [inline android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt]: Add instrumentation tests to cover that it works as expected after rotation? That was the most common problem we tried to address.

File: android/libraries/rib-base/src/main/java/com/badoo/ribs/plugins/RibsPlugins.kt [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+    private const val TAG = "RIBs"
+
+    var noRequestCodeListenersErrorHandler
+        : (requestCode: Int,
+           internalRequestCode: Int,
+           internalGroup: Int,
+           event: RequestCodeBasedEventStream.RequestCodeBasedEvent) -> Int =
+        { requestCode, internalRequestCode, internalGroup, event ->
+            Log.e(TAG, "There's no one listening for request code event! " +
```
[the remark this answers is not in the document]
Comment (lukaville) [reply android/libraries/rib-base/src/main/java/com/badoo/ribs/plugins/RibsPlugins.kt]: Forgot about this class, converted RIBs to Kotlin and moved this callback there 👍

File: android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt (hunk 1 above)
Comment (lukaville) [reply android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt]: I've tried to emulate activity restart in the current tests but had no success with this. Android in a real environment never destroys the previous activities for the same app (it may happen only if we open another app). In espresso, we can restart the current activity but here we need to restart activity that is already in the back stack.

As we discussed earlier (when we faced emulator problems) it is necessary to develop tools that will supervise test running and probably it's not worth to do this and it will be enough to have only unit tests for this.

Comment (zsoltk) [reply android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt]: Then maybe manually call save / detach / restore cycle on a test rib, set request code based request before cycle, check result is delivered after cycle? Every time it failed, it was related to above scenario. I wouldn't feel safe without covering it with tests somehow.

Comment (lukaville) [reply android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt]: Found a way how to ignore activity start in the test. A bit hacky but simple: I just overrode `startActivity` method, so it doesn't launch actual activity and then I manually call `onActivityResult`. Please check

File: android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt [hunk 3]
```diff
@@ -0,0 +1,113 @@
+package com.badoo.ribs.util
+
+import android.support.annotation.VisibleForTesting
+import android.util.Log
+import com.badoo.ribs.android.requestcode.RequestCodeBasedEventStream
+
+object RIBs {
```
Comment (zsoltk) [inline android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt]: I think I also kotlinified this class in my last PR, and added some functionality. Not sure why it doesn't complain, so please recheck.

File: android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+        /**
+         * Called when we received a result for request code but there is no listeners for it
+         *
+         * If no errorHandler is set, the default implementation of this will print a warning
+         * to logcat.
+         */
+        fun handleNoRequestCodeListenersError(requestCode: Int,
+                                              internalRequestCode: Int,
+                                              internalGroup: Int,
+                                              event: RequestCodeBasedEventStream.RequestCodeBasedEvent)
```
Comment (zsoltk) [inline android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt]: Weird indentation

File: android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt (hunk 3 above)
Comment (lukaville) [reply android/libraries/rib-base/src/main/java/com/badoo/ribs/util/RIBs.kt]: Your RIBs class was in a different package. Fixed

File: android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt (hunk 1 above)
Comment (lukaville) [reply android/libraries/rib-base/src/test/java/com/badoo/ribs/android/requestcode/RequestCodeBasedEventStreamImplTest.kt]: I've added one more test case that fails when we do not pass bundle to request code registry.
We are saving request code map to bundle only to avoid problems when we have a collision (in other cases it will work fine because we will generate the same group ids for the same RIB ids). I wrote a test that starts activity using ids that have different String values but have the same hash code.
