### PR TITLE
Fix view is not attached

### LINKED ISSUE #359: View is not attached after restoring from Bundle
To reproduce we need to have next setup:
```
|--> MainContainerRIB
|--|--> ChildContainerRIB1
|--|--|--> ChildRib1
|--|--> ChildRIB2
```

1. Enable Don't keep activities
2. Start with `ChildContainerRIB1.ChildRIB1` configuration
3. Push `ChildRIB2` configuration
4. Hide/unhide application to trigger saving configuration in Bundle
5. Reopen app
6. Move back to `ChildContainerRIB1`.
7. `ChildRIB1` view is not attached.

Explanation of what is happening:
- Check `RoutingStatePool.individual()`
- When pushing next configurations we invoke `Effect.Individual.PendingDeactivateTrue` for `ChildRib1` which add this key into `pendingDeactivate`
- Then we receive `Effect.Individual.Deactivated` but we do not clear `ChildRIB1` key from `pendingDeactivate`
- When saving state into Bundle we have a logic which checks `pendingDeactivate` and moves it to the `INACTIVE` state.

```
com.badoo.ribs.routing.state.feature.state.WorkingState.toSavedState()
...
!pendingDeactivate.contains(entry.key) -> original
   else -> original.withActivationState(
      activationState = RoutingContext.ActivationState.INACTIVE
)
...
```

- After restoring that Node is moved to `INACTIVE` state and then is never becomes activated.
- Activating is responsibility of `WakeUpAction` which activates only `SLEEPING` nodes.

Solution proposed is to cleanup `pendingDeactivate` and `pendingRemoval` when receiving `Removed|Activated|Deactivated` effects.

### PR DESCRIPTION
**Pull request by Nublo**
Closes #359

### CODE REVIEW

**Review by CherryPerry — APPROVED** [review]

File: libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/RoutingStatePoolTest.kt [hunk 1]
```diff
@@ -633,6 +633,17 @@ class RoutingStatePoolTest {
...
+    @Test
+    fun `On Deactivate, Node routing is removed from pendingDeactivate`() {
+        createEmptyPool()
+        pool.accept(Transaction.from(
+            Add(helperContentViewParented1.routing),
+            Deactivate(helperContentViewParented1.routing)
+        ))
+
+        assertEquals(true, pool.state.pendingDeactivate.isEmpty())
+    }
```
Comment (zsoltk) [inline libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/RoutingStatePoolTest.kt:645]: This doesn't seem to prove that it's removed correctly only that it's not there in the end – if it was never there in the first place, then this test passes just the same.

Comment (Nublo) [reply libraries/rib-base/src/test/java/com/badoo/ribs/routing/state/RoutingStatePoolTest.kt:659]: Added one more test that verifies, that `pool.state.pendingDeactivate` contains `helperContentViewParented1.routing` during `DeactivateAction`

**Review by zsoltk — APPROVED** [review]

**Review by SamuPS — APPROVED** [review]
